config/routes.rb
Rails.application.routes.draw do
  get "/contacts" => "contacts#index"
  get "/contacts/new" => "contacts#new"
  post "/contacts" => "contacts#create"
  get "/contacts/:contact_id" => "contacts#show", as: :contact_show
end

app/models/address_book_db.rb
class AddressBookDb < ActiveRecord::Base
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def index
		@contacts = Contact.order("name ASC")
	end

	def new
		@contact = Contact.new
	end

	def create

		if ((params[:contact][:name] == "") || (params[:contact][:address] == ""))
			redirect_to "/contacts/new"
		else
			Contact.create({
				name:params[:contact][:name],
				address:params[:contact][:address],
				phone_number:params[:contact][:phone_number],
				email:params[:contact][:email]
				})
			redirect_to "/contacts"
		end
	end

	def show
		@contact = Contact.find_by(id: params[:contact_id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/index.html.erb
<h3>Contact list</h3>
<hr>
<ul>
<% @contacts.each do |contact| %>
<li><a href=<%=contact_show_path(contact)%>><%= contact.name %></a></li>
<%end%>
</ul>
<hr>
<button><a href=<%= contacts_new_path%>>New contact</a></button>

app/views/contacts/new.html.erb
<h3>Add a New Contact</h3>

<%= form_for @contact do |c| %>
	<div>
		<%= c.text_field :name, placeholder:"name" %>
	</div><br>
	<div>
		<%= c.text_field :address, placeholder:"address" %>
	</div><br>
	<div>
		<%= c.number_field :phone_number, placeholder:"phone number"  %>
	</div><br>
	<div>
		<%= c.email_field :email, placeholder:"e-mail address" %>
	</div><br>
	<div>
  		<%= c.submit "Add a new contact" %>
  		<button><a href=<%=contacts_path%>>Back to contact list</a></button>
  	</div>
<%end%>

app/views/contacts/show.html.erb
<h3>Contact Information</h3>

<p><img src="http://a.deviantart.net/avatars/m/r/mrherrimanplz.gif?1"><p>

<ul>
<li><strong>Name:</strong> <%= @contact.name %></li>
<li><strong>Address:</strong> <%= @contact.address %></li>
<li><strong>Phone number:</strong> <%= @contact.phone_number %></li>
<li><strong>Email Address:</strong> <%= @contact.email %></li>
</ul>
<hr>
<button><a href=<%=contacts_path%>>Back to contact list</a></button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AddressBook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>